"""Add study_goal to User model

Revision ID: 452d8dc72e9d
Revises: a28df9907027
Create Date: 2025-07-15 00:10:14.224897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452d8dc72e9d'
down_revision = 'a28df9907027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('study_goal')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_goal', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('study_goal')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_goal', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
