"""Add study_goal to User

Revision ID: a28df9907027
Revises: 04d22e18cd5a
Create Date: 2025-07-15 00:08:10.702814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28df9907027'
down_revision = '04d22e18cd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_goal', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('study_goal')

    # ### end Alembic commands ###
