"""Add status, school, social_link to User

Revision ID: c98aded47dfa
Revises: 452d8dc72e9d
Create Date: 2025-07-15 02:07:10.171500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98aded47dfa'
down_revision = '452d8dc72e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('social_link', sa.String(length=140), nullable=True))
        batch_op.drop_column('study_goal')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('study_goal', sa.TEXT(), nullable=True))
        batch_op.drop_column('social_link')
        batch_op.drop_column('school')
        batch_op.drop_column('status')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
