"""Add category and custom_category to Post

Revision ID: e3cfc05a9420
Revises: 4754970639e4
Create Date: 2025-07-13 13:40:24.783092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cfc05a9420'
down_revision = '4754970639e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('custom_category', sa.String(length=50), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('custom_category')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
